/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'agents': RouteRecordInfo<'agents', '/agents', Record<never, never>, Record<never, never>>,
    'agents-id': RouteRecordInfo<'agents-id', '/agents/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'clients': RouteRecordInfo<'clients', '/clients', Record<never, never>, Record<never, never>>,
    'clients-id': RouteRecordInfo<'clients-id', '/clients/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'clients-coponents-agent-call-logs': RouteRecordInfo<'clients-coponents-agent-call-logs', '/clients/coponents/AgentCallLogs', Record<never, never>, Record<never, never>>,
    'clients-coponents-agent-visit-logs': RouteRecordInfo<'clients-coponents-agent-visit-logs', '/clients/coponents/AgentVisitLogs', Record<never, never>, Record<never, never>>,
    'clients-coponents-client-info': RouteRecordInfo<'clients-coponents-client-info', '/clients/coponents/ClientInfo', Record<never, never>, Record<never, never>>,
    'clients-coponents-collateral-info': RouteRecordInfo<'clients-coponents-collateral-info', '/clients/coponents/CollateralInfo', Record<never, never>, Record<never, never>>,
    'clients-coponents-guarantor-info': RouteRecordInfo<'clients-coponents-guarantor-info', '/clients/coponents/GuarantorInfo', Record<never, never>, Record<never, never>>,
    'clients-coponents-payment-info': RouteRecordInfo<'clients-coponents-payment-info', '/clients/coponents/PaymentInfo', Record<never, never>, Record<never, never>>,
    'department': RouteRecordInfo<'department', '/department', Record<never, never>, Record<never, never>>,
    'district': RouteRecordInfo<'district', '/district', Record<never, never>, Record<never, never>>,
    'fourth': RouteRecordInfo<'fourth', '/fourth', Record<never, never>, Record<never, never>>,
    'loan-portfolio': RouteRecordInfo<'loan-portfolio', '/loan-portfolio', Record<never, never>, Record<never, never>>,
    'local-code': RouteRecordInfo<'local-code', '/local-code', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'neighborhood': RouteRecordInfo<'neighborhood', '/neighborhood', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'rbac': RouteRecordInfo<'rbac', '/rbac', Record<never, never>, Record<never, never>>,
    'region': RouteRecordInfo<'region', '/region', Record<never, never>, Record<never, never>>,
    'user': RouteRecordInfo<'user', '/user', Record<never, never>, Record<never, never>>,
  }
}
